version: '2.1'

services:
  mern:
    image: mern
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 4000:4000
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js